### ISSUE TITLE
 Error Related to csr.json File During Generation of Litex.resc and Litex.repl Files

### ISSUE THREAD

**Issue by fdsgdshn** [litex-hub/litex-boards#508] opened 2023-06-07 09:13 UTC
Hi,

I came across your webpage that explains how to create litex.repl and litex.resc files to use Litex in [Generate Renode simulation](https://github.com/enjoy-digital/litex/wiki/Generate-Renode-simulation).  I cannot obtain these platform and script files. Can you assist me with this issue?

command 1:
````
python3 litex/boards/targets/arty.py --cpu-type vexriscv --with-ethernet --csr-json csr.json
````
command 2:
````
litex_json2renode csr.json --resc litex.resc --repl litex.repl --bios-binary soc_ethernetsoc_arty/software/bios/bios.bin
````

I'm getting an error indicating that the csr.json file does not contain the "config_cpu_count" parameter. The error occurs in litex/build/lib/litex/tools/litex_json2renode.py, specifically in line 217, where it tries to access csr['constants']['config_cpu_count'], resulting in a KeyError: 'config_cpu_count'.

Note: Since the repository is regularly updated, the path does not match the current directory. However, I have already edited it accordingly.

Thanks!

**Comment by enjoy-digital** [comment] 2023-09-27 09:18
Hi @fdsgdshn,

sorry for the delay, with upstream code, I'm not able to reproduce the issue:

````
python3 -m litex_boards.targets.digilent_arty --cpu-type vexriscv --with-ethernet --csr-json csr.json --build --no-compile
litex_json2renode csr.json --resc litex.resc --repl litex.repl --bios-binary soc_ethernetsoc_arty/software/bios/bios.bin
````

so this has been fixed since then or version was not up to date. We can probably close this.

**Closed by enjoy-digital** 2023-09-27 09:18 UTC
